/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game;

import java.awt.GridLayout;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author Ali Sezer
 */
public class loto extends javax.swing.JFrame {
JButton[] buttons = new JButton[49]; 
int[] numbers = new int[6];
/**
     * Creates new form loto
     */
    public loto() {
        initComponents();
        setLocationRelativeTo(null);
        GridLayout gridLayout = new GridLayout(7,7);
        Pn_buttons.setLayout(gridLayout);
        generateButtons();
        disablebuttons();
                
    }
    public void generateButtons(){
        for(int i=0;i<49;i++){
        buttons[i]=new JButton(String.valueOf(i+1));
        Pn_buttons.add(buttons[i]);
        }
    }
    public void disablebuttons(){
    for(int i=0;i<49;i++){
    buttons[i].setEnabled(false);
    buttons[i].setComponentPopupMenu(null);
    }
    }
    public void generatenumbers(){
    Arrays.fill(numbers,0);
    Random rnd=new Random();
    int number, j;
    for(int i=0;i<6;i++){
    while(true){
    number=rnd.nextInt(49)+1;
    for(j=0;j<numbers.length;j++)
        if(numbers[j]==number)
            break;
    if(j==numbers.length){
    numbers[i]=number;
    break;
    }
    
    
    }
    
    
    }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_clilck = new javax.swing.JPopupMenu();
        mnitem_dislike = new javax.swing.JMenuItem();
        Pn_buttons = new javax.swing.JPanel();
        Buton = new javax.swing.JButton();

        mnitem_dislike.setText("Bu Sayiyi Begenmedim");
        mnitem_dislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitem_dislikeActionPerformed(evt);
            }
        });
        popup_clilck.add(mnitem_dislike);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pn_buttons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout Pn_buttonsLayout = new javax.swing.GroupLayout(Pn_buttons);
        Pn_buttons.setLayout(Pn_buttonsLayout);
        Pn_buttonsLayout.setHorizontalGroup(
            Pn_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Pn_buttonsLayout.setVerticalGroup(
            Pn_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        Buton.setText("Oyna");
        Buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pn_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(Buton)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Pn_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonActionPerformed
        generatenumbers();
        disablebuttons();
        for (int i = 0; i < numbers.length; i++) {
            buttons[numbers[i]-1].setEnabled(true);
             buttons[numbers[i]-1].setComponentPopupMenu(popup_clilck);
            
        }
    }//GEN-LAST:event_ButonActionPerformed
    public int regenerateNumber(int Number,int index){
    Random rnd=new Random();
    int genNumber=0,j;
    while(true){
        genNumber=rnd.nextInt(49)+1;
        for (j = 0; j < numbers.length; j++) 
            if(numbers[j]==genNumber)
                break;
            if(j==numbers.length){
            numbers[index]=genNumber;
            break;
                    }
            
        }
        return genNumber;
    }
    
    
    
    
    private void mnitem_dislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitem_dislikeActionPerformed
       int selectedNumber= Integer.parseInt(((JButton)popup_clilck.getInvoker()).getText());
       int index=-1;
        for (int i = 0; i < numbers.length; i++) {
        index=i;
        break;
      
        }
        int newNumber =  regenerateNumber(selectedNumber,index);
        buttons[selectedNumber-1].setEnabled(false);
        buttons[selectedNumber-1].setComponentPopupMenu(null);
        
        buttons[newNumber-1].setEnabled(true);
        buttons[newNumber-1].setComponentPopupMenu(popup_clilck);
        
    }//GEN-LAST:event_mnitem_dislikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buton;
    private javax.swing.JPanel Pn_buttons;
    private javax.swing.JMenuItem mnitem_dislike;
    private javax.swing.JPopupMenu popup_clilck;
    // End of variables declaration//GEN-END:variables
}
